const CURRENCIES = {
  GET_CURRENCIES: 'GET_CURRENCIES',
  GET_CURRENCIES_SUCCESS: 'GET_CURRENCIES_SUCCESS',
  GET_CURRENCIES_ERROR: 'GET_CURRENCIES_ERROR',
  SET_BASE_CURRENCY: 'SET_BASE_CURRENCY',
  SET_FAVORITE: 'SET_FAVORITE',
  SET_FAVORITE_SUCCESS: 'SET_FAVORITE_SUCCESS',
  SET_FAVORITE_IDS: 'SET_FAVORITE_IDS',
};

export {
  CURRENCIES,
};
